### PR TITLE
Also resample if channel count is different

### LINKED ISSUE #48: Audio bitrate is corrupted
When recording with the TestApp using default settings + Audio input the resulting video has a time compressed/stretched audio (depending on the player). I inspected the files using MediaInfo:

```
Duration                                 : 3 s 334 ms
Bit rate mode                            : Constant
Bit rate                                 : 48.0 kb/s
Nominal bit rate                         : 96.0 kb/s
Channel(s)                               : 2 channels
```

There should be no nominal bit rate and the Bit rate should be at 96.0 kb/s.

Another recording with debugging enabled produced the following:

```
Bit rate mode                            : Constant
Bit rate                                 : 56.4 kb/s
Nominal bit rate                         : 96.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 148 Bytes (0%)
```
And the according debug output:
```
Resampled audio from 16000hz to 48000hz
Wrote frame with start pos 0 ms and with duration 0 ms
Inserted 80 bytes of silence
Wrote audio sample with start pos 0 ms and with duration 0 ms
Received stop event after 734 passes and 58720 frames
Received stop event after 742 passes and 0 frames
Exiting recording task
```

### PR DESCRIPTION
**Pull request by hakito**
Fixes #48

### CODE REVIEW

**Comment by hakito** [comment]
Fixes #53 

Now the recorded video has a proper length when recording with variable frame rate. However when using Audio together with VFR there is some stuttering.

**Comment by sskodje** [comment]
Thanks, i'll check it out

**Comment by sskodje** [comment]
For the recording when the picture does not change, there is a fundamental flaw in the existing logic that should be addressed. As it is now, if it records a static image, and nothing changes, it just keeps buffering audio ad infinitum, without pushing it to the encoder, which is eventually going to lead to memory problems.

I just tried it, and got 
`Error: Writing of video frame with start pos 126153 ms failed: Not enough memory resources are available to complete this operation.`

I think either variable framerate needs to push at a max interval, like every second, or it needs to be rewritten so it always pushes to encoder at min framerate, e.g. every 33ms at 30 fps, and then just have a floating framerate between there and whatever the screen outputs.

**Comment by hakito** [comment]
> Edit: perhaps it's possible to push audio only to encoder, and just provide video frames as they become available. But i'm probably overthinking it.

To this sounds like the most obvious solution. It's not nescessary that audio and video streams have the same frame rate.

Actually I am not sure if VFR brings really that much benefits at all. According to the docs duplicate [frames are dropped anyway](https://docs.microsoft.com/en-us/windows/win32/medfound/howcanavideostreamencodedusingqualitybasedvbrhavef). This i probably half the truth. Although the resulting video does not seem to grow in size, the frame count is still going up.

I'll modify the code so audio frames are pushed independently.

**Comment by sskodje** [comment]
I pushed a commit that fixed the issue with still images by pushing at least every second and dropping last fram, as well as the problem with the glitching audio. That was due to to on frames with very short duration, the audio capture would have no data, so the code would zero pad, and that lead to the glitches. I'll close this PR, since your changes are cherry picked in, so you can make a new one if you want.

**Pull request closed without merging**
