### PR TITLE
Fix v1.8 memory issue

### LINKED ISSUE #55: Write error in v1.8
I just did some test recordings with the 1.8 lib and after a few seconds the recording stopped automatically with an error. The cause seems to be in 

f577fd5f5a5bf16967d983d8e7b13467ccba42c1

```
Recording started
Press ESC to stop recording or enter to pause
Elapsed: 24s:828msFinishing encoding
Elapsed: 24s:843msRecorder is idle
Elapsed: 25s:866msRecording failed: Write error in video encoder.
Elapsed: 32s:893ms
```

I tried several times with
872f9a0e7759f3931bb9df4051a9e01bde20d0c6
and had no problem.

### PR DESCRIPTION
**Pull request by hakito**
ARGHH!!! It seems to be a compiler bug! I tried to analyze where this strange duration comes from. So I inserted the following lines before EnqueueFrame:

```c++
model.Duration = durationSinceLastFrame100Nanos;
model.StartPos = lastFrameStartPos;
LOG(L"Duration %llu %llu", durationSinceLastFrame100Nanos, model.Duration);
if (recordAudio) {
	model.Audio = GrabAudioFrame(pLoopbackCaptureOutputDevice, pLoopbackCaptureInputDevice);
}
LOG(L"Duration %llu %llu", durationSinceLastFrame100Nanos, model.Duration);
```

And guess what the log shows sometimes:

```
Duration 346575 346575
Duration 346575 2061584648655
```

Some time later I just thought this can't be. The model is created on the stack and only used in the current thread. There is no operation that changes the value of duration.

So I was thinking of a compiler bug and I tried it with VS 2019 compiler and the recording is working.

Fixes #55

### CODE REVIEW

**Comment by sskodje** [comment]
Wow, nice find. That's surprising!

**Comment by hakito** [comment]
I appended some minor fixes. Would be great If you could do a new release after the review.

**Comment by sskodje** [comment]
I'm on second thought a bit skeptical about changing the platform tools, since it will make the code only compatible with VS 2019, which i'd like to avoid unnecesarily, and I have not found any issues using platform tools 141 on my end. With all the other issues you have, there must be some other underlying issue. Can you try repairing your visual studio and see if it fixes it?

**Comment by hakito** [comment]
I did now an A/B test on 8 different computers. No difference in the results when using hardware or software for the encoding.

With **v141**
- 3x i7 CRASH
- 2x i5 CRASH
- i3 CRASH
- Atom x5-z8350 CRASH
- Amd Athlon 64 x2 was OK

With **v142** all were OK

Unfortunateley this old AMD was the only AMD cpu i had for testing. A Ryzen is already ordered but I can't test it before monday. Which systems did you get it working with?

I also tried compiling with different computers and with the version 1.8.0 from the nuget package.

If you want to stay with VS 2019 you can also just install the VS 2019 build tools.

**Comment by sskodje** [comment]
Sorry for slow responding, i've been a bit busy with other stuff.

Yeah you're probably right, it doesn't really matter. I'll merge the changes soon.  But really, compiling for 142 or 141 makes no difference for me, on any of the machines available to me. All laptops and desktop with intel i5 or i7 though, i have no AMD machines to test with. Out of curiosity i downloaded a fresh [windows 10 dev environment VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) from microsoft to compile with vs2019 and build tools 141, and it still made no difference, all is working. Even though upgrading to 142 will fix it, you probably still have some sort of issue with your VS installation responsible for the bugs.

**Comment by hakito** [comment]
No problem. Do you think you can merge it back this week?

**Comment by sskodje** [comment]
I merged it in by cherry-pick, so closing this. It's much easier to merge if you create a new branch for PR with only  the commits you want to merge btw, so it does not include irrelevant and conflicting stuff.

**Pull request closed without merging**
